name: flavourfi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/cooking.jpeg
    - lib/assets/images/ingredients.jpeg
    - lib/assets/images/diet.jpg
    - lib/assets/images/healthy-diet.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
